---
# roles/postgresql_database_deployment/handlers/main.yml
- name: Restart postgresql
  ansible.builtin.service:
    name: "{{ postgresql_service_name[ansible_facts['os_family']] }}"
    state: restarted

- name: Reload postgresql
  ansible.builtin.service:
    name: "{{ postgresql_service_name[ansible_facts['os_family']] }}"
    state: reloaded
